package net.osbee.app.restservicetest.model.actions;

import com.vaadin.ui.AbstractLayout;
import com.vaadin.ui.Component;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.Panel;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Properties;
import java.util.UUID;
import org.eclipse.e4.core.contexts.ContextInjectionFactory;
import org.eclipse.e4.core.contexts.IEclipseContext;
import org.eclipse.e4.core.di.extensions.EventUtils;
import org.eclipse.e4.core.services.translation.TranslationService;
import org.eclipse.e4.ui.di.Focus;
import org.eclipse.e4.ui.model.application.MApplication;
import org.eclipse.e4.ui.model.application.commands.MBindingContext;
import org.eclipse.e4.ui.model.application.commands.MBindingTable;
import org.eclipse.e4.ui.model.application.commands.MCommand;
import org.eclipse.e4.ui.model.application.commands.MHandler;
import org.eclipse.e4.ui.model.application.commands.MKeyBinding;
import org.eclipse.e4.ui.model.application.commands.impl.CommandsFactoryImpl;
import org.eclipse.e4.ui.model.application.ui.MContext;
import org.eclipse.e4.ui.model.application.ui.MUIElement;
import org.eclipse.e4.ui.model.application.ui.advanced.MPerspective;
import org.eclipse.e4.ui.model.application.ui.advanced.MPerspectiveStack;
import org.eclipse.e4.ui.model.application.ui.basic.MPart;
import org.eclipse.e4.ui.model.application.ui.basic.MTrimmedWindow;
import org.eclipse.e4.ui.model.application.ui.menu.ItemType;
import org.eclipse.e4.ui.model.application.ui.menu.MHandledToolItem;
import org.eclipse.e4.ui.model.application.ui.menu.MToolBar;
import org.eclipse.e4.ui.model.application.ui.menu.MToolBarSeparator;
import org.eclipse.e4.ui.model.application.ui.menu.MToolControl;
import org.eclipse.e4.ui.model.application.ui.menu.impl.MenuFactoryImpl;
import org.eclipse.e4.ui.workbench.modeling.EModelService;
import org.eclipse.osbp.core.api.persistence.IPersistenceService;
import org.eclipse.osbp.ecview.core.common.context.IViewContext;
import org.eclipse.osbp.eventbroker.EventBrokerMsg;
import org.eclipse.osbp.osgi.hybrid.api.HybridVaadinVaaclipseConnector;
import org.eclipse.osbp.preferences.ProductConfiguration;
import org.eclipse.osbp.runtime.common.annotations.IsDirty;
import org.eclipse.osbp.runtime.common.annotations.IsNew;
import org.eclipse.osbp.runtime.common.annotations.IsPositioned;
import org.eclipse.osbp.runtime.common.annotations.IsValid;
import org.eclipse.osbp.runtime.common.event.EventDispatcherEvent;
import org.eclipse.osbp.runtime.common.event.EventDispatcherEvent.EventDispatcherCommand;
import org.eclipse.osbp.runtime.common.event.EventDispatcherEvent.EventDispatcherDataTag;
import org.eclipse.osbp.ui.api.contextfunction.ICommandsProvider;
import org.eclipse.osbp.ui.api.e4.IE4Dialog;
import org.eclipse.osbp.ui.api.e4.IE4Focusable;
import org.eclipse.osbp.ui.api.e4.IE4Table;
import org.eclipse.osbp.ui.api.perspective.IPerspectiveProvider;
import org.eclipse.osbp.ui.api.themes.EnumCssClass;
import org.eclipse.osbp.ui.api.themes.IThemeResourceService;
import org.eclipse.osbp.ui.api.themes.IThemeResourceService.ThemeResourceType;
import org.eclipse.osbp.ui.api.useraccess.AbstractAuthorization.Action;
import org.eclipse.osbp.ui.api.useraccess.AbstractAuthorization.Group;
import org.eclipse.osbp.utils.vaadin.MDXDialog;
import org.eclipse.osbp.vaaclipse.api.VaadinExecutorService;
import org.eclipse.osbp.xtext.action.ChartActionEnum;
import org.eclipse.osbp.xtext.action.DatainterchangeActionEnum;
import org.eclipse.osbp.xtext.action.DialogActionEnum;
import org.eclipse.osbp.xtext.action.ReportActionEnum;
import org.eclipse.osbp.xtext.action.SelectWorkloadActionEnum;
import org.eclipse.osbp.xtext.action.TableActionEnum;
import org.eclipse.osbp.xtext.action.TaskActionEnum;
import org.eclipse.osbp.xtext.action.UIActionEnum;
import org.eclipse.osbp.xtext.action.WorkflowActionEnum;
import org.eclipse.osbp.xtext.action.common.E4Helper;
import org.eclipse.osbp.xtext.action.common.TaskHelper;
import org.eclipse.osbp.xtext.datainterchange.common.WorkerThreadRunnable;
import org.eclipse.osbp.xtext.datainterchange.common.WorkerThreadRunnable.Parameter;
import org.osgi.framework.FrameworkUtil;
import org.osgi.service.event.Event;

@org.osgi.service.component.annotations.Component(service = ICommandsProvider.class)
@SuppressWarnings("all")
public class CommandsProvider implements ICommandsProvider {
  public CommandsProvider() {
    
  }
  
  @Override
  public void init(final MApplication application) {
    if(!application.getBindingTables().isEmpty()) {
    	MBindingTable bindingTable = application.getBindingTables().get(0);
    	MKeyBinding keyBinding;
    	MCommand command;
    	MHandler commandHandler;
    	command = CommandsFactoryImpl.eINSTANCE.createCommand();
    	command.setElementId("net.osbee.app.restservicetest.model.actions.newItem");
    	command.setCommandName("newItem");
    	application.getCommands().add(command);
    	commandHandler = CommandsFactoryImpl.eINSTANCE.createHandler();
    	commandHandler.setElementId("net.osbee.app.restservicetest.model.actions.newItemHandler");
    	commandHandler.setCommand(command);
    	commandHandler.setContributionURI("bundleclass://"+FrameworkUtil.getBundle(net.osbee.app.restservicetest.model.actions.NewItemAction.class).getSymbolicName()+"/net.osbee.app.restservicetest.model.actions.NewItemAction");
    	application.getHandlers().add(commandHandler);
    	keyBinding = CommandsFactoryImpl.eINSTANCE.createKeyBinding();
    	keyBinding.setElementId("net.osbee.app.restservicetest.model.actions.newItemKeybinding");
    	keyBinding.setKeySequence("CTRL+ALT+N");
    	keyBinding.setCommand(command);
    					bindingTable.getBindings().add(keyBinding);
    	command = CommandsFactoryImpl.eINSTANCE.createCommand();
    	command.setElementId("net.osbee.app.restservicetest.model.actions.saveItem");
    	command.setCommandName("saveItem");
    	application.getCommands().add(command);
    	commandHandler = CommandsFactoryImpl.eINSTANCE.createHandler();
    	commandHandler.setElementId("net.osbee.app.restservicetest.model.actions.saveItemHandler");
    	commandHandler.setCommand(command);
    	commandHandler.setContributionURI("bundleclass://"+FrameworkUtil.getBundle(net.osbee.app.restservicetest.model.actions.SaveItemAction.class).getSymbolicName()+"/net.osbee.app.restservicetest.model.actions.SaveItemAction");
    	application.getHandlers().add(commandHandler);
    	keyBinding = CommandsFactoryImpl.eINSTANCE.createKeyBinding();
    	keyBinding.setElementId("net.osbee.app.restservicetest.model.actions.saveItemKeybinding");
    	keyBinding.setKeySequence("CTRL+ALT+S");
    	keyBinding.setCommand(command);
    					bindingTable.getBindings().add(keyBinding);
    	command = CommandsFactoryImpl.eINSTANCE.createCommand();
    	command.setElementId("net.osbee.app.restservicetest.model.actions.deleteItem");
    	command.setCommandName("deleteItem");
    	application.getCommands().add(command);
    	commandHandler = CommandsFactoryImpl.eINSTANCE.createHandler();
    	commandHandler.setElementId("net.osbee.app.restservicetest.model.actions.deleteItemHandler");
    	commandHandler.setCommand(command);
    	commandHandler.setContributionURI("bundleclass://"+FrameworkUtil.getBundle(net.osbee.app.restservicetest.model.actions.DeleteItemAction.class).getSymbolicName()+"/net.osbee.app.restservicetest.model.actions.DeleteItemAction");
    	application.getHandlers().add(commandHandler);
    	keyBinding = CommandsFactoryImpl.eINSTANCE.createKeyBinding();
    	keyBinding.setElementId("net.osbee.app.restservicetest.model.actions.deleteItemKeybinding");
    	keyBinding.setKeySequence("CTRL+ALT+D");
    	keyBinding.setCommand(command);
    					bindingTable.getBindings().add(keyBinding);
    	command = CommandsFactoryImpl.eINSTANCE.createCommand();
    	command.setElementId("net.osbee.app.restservicetest.model.actions.cancelItem");
    	command.setCommandName("cancelItem");
    	application.getCommands().add(command);
    	commandHandler = CommandsFactoryImpl.eINSTANCE.createHandler();
    	commandHandler.setElementId("net.osbee.app.restservicetest.model.actions.cancelItemHandler");
    	commandHandler.setCommand(command);
    	commandHandler.setContributionURI("bundleclass://"+FrameworkUtil.getBundle(net.osbee.app.restservicetest.model.actions.CancelItemAction.class).getSymbolicName()+"/net.osbee.app.restservicetest.model.actions.CancelItemAction");
    	application.getHandlers().add(commandHandler);
    	keyBinding = CommandsFactoryImpl.eINSTANCE.createKeyBinding();
    	keyBinding.setElementId("net.osbee.app.restservicetest.model.actions.cancelItemKeybinding");
    	keyBinding.setKeySequence("CTRL+ALT+Z");
    	keyBinding.setCommand(command);
    					bindingTable.getBindings().add(keyBinding);
    	command = CommandsFactoryImpl.eINSTANCE.createCommand();
    	command.setElementId("net.osbee.app.restservicetest.model.actions.print");
    	command.setCommandName("print");
    	application.getCommands().add(command);
    	commandHandler = CommandsFactoryImpl.eINSTANCE.createHandler();
    	commandHandler.setElementId("net.osbee.app.restservicetest.model.actions.printHandler");
    	commandHandler.setCommand(command);
    	commandHandler.setContributionURI("bundleclass://"+FrameworkUtil.getBundle(net.osbee.app.restservicetest.model.actions.PrintAction.class).getSymbolicName()+"/net.osbee.app.restservicetest.model.actions.PrintAction");
    	application.getHandlers().add(commandHandler);
    	command = CommandsFactoryImpl.eINSTANCE.createCommand();
    	command.setElementId("net.osbee.app.restservicetest.model.actions.printDownload");
    	command.setCommandName("printDownload");
    	application.getCommands().add(command);
    	commandHandler = CommandsFactoryImpl.eINSTANCE.createHandler();
    	commandHandler.setElementId("net.osbee.app.restservicetest.model.actions.printDownloadHandler");
    	commandHandler.setCommand(command);
    	commandHandler.setContributionURI("bundleclass://"+FrameworkUtil.getBundle(net.osbee.app.restservicetest.model.actions.PrintDownloadAction.class).getSymbolicName()+"/net.osbee.app.restservicetest.model.actions.PrintDownloadAction");
    	application.getHandlers().add(commandHandler);
    }
    
  }
}
